// Copyright 2026 The Parca Authors
// SPDX-License-Identifier: Apache-2.0

// Shared error USDT probe helper. Fires the "error" probe from either backend
// (CUPTI/NVIDIA and MSPTI/Ascend) and from env_config. Header-only inline so
// it can be included by multiple translation units in one shared object.
//
// Also hosts the two code->name lookup tables (cudaErrorName / aclErrorName).
// Both avoid dlsym() because the runtime libraries are loaded RTLD_LOCAL, so
// the symbol lookups would fail; a static switch table is the reliable path.

#ifndef COLAGPU_ERROR_H_
#define COLAGPU_ERROR_H_

// USDT probes — must come before any header that might include <sys/sdt.h>,
// so that _SDT_HAS_SEMAPHORES is defined first.
#include "probes.h"

#include <cstdint>

namespace parcagpu {

// Fire the error USDT probe. Callable from any translation unit.
__attribute__((noinline)) inline void
fireError(int32_t code, const char *message, const char *component) {
  COLAGPU_ERROR(code, message, component);
}

// ---------------------------------------------------------------------------
// CUDA / CUPTI error names.
// ---------------------------------------------------------------------------

// Static lookup table mapping cudaError codes to their symbolic names.
// Avoids dlsym(cudaGetErrorName) which fails when libcudart is loaded with
// RTLD_LOCAL.
static inline const char *cudaErrorName(int code) {
  switch (code) {
  case 1:
    return "cudaErrorInvalidValue";
  case 2:
    return "cudaErrorMemoryAllocation";
  case 3:
    return "cudaErrorInitializationError";
  case 4:
    return "cudaErrorCudartUnloading";
  case 5:
    return "cudaErrorProfilerDisabled";
  case 6:
    return "cudaErrorProfilerNotInitialized";
  case 7:
    return "cudaErrorProfilerAlreadyStarted";
  case 8:
    return "cudaErrorProfilerAlreadyStopped";
  case 9:
    return "cudaErrorInvalidConfiguration";
  case 12:
    return "cudaErrorInvalidPitchValue";
  case 13:
    return "cudaErrorInvalidSymbol";
  case 16:
    return "cudaErrorInvalidHostPointer";
  case 17:
    return "cudaErrorInvalidDevicePointer";
  case 18:
    return "cudaErrorInvalidTexture";
  case 19:
    return "cudaErrorInvalidTextureBinding";
  case 20:
    return "cudaErrorInvalidChannelDescriptor";
  case 21:
    return "cudaErrorInvalidMemcpyDirection";
  case 22:
    return "cudaErrorAddressOfConstant";
  case 23:
    return "cudaErrorTextureFetchFailed";
  case 24:
    return "cudaErrorTextureNotBound";
  case 25:
    return "cudaErrorSynchronizationError";
  case 26:
    return "cudaErrorInvalidFilterSetting";
  case 27:
    return "cudaErrorInvalidNormSetting";
  case 28:
    return "cudaErrorMixedDeviceExecution";
  case 31:
    return "cudaErrorNotYetImplemented";
  case 32:
    return "cudaErrorMemoryValueTooLarge";
  case 34:
    return "cudaErrorStubLibrary";
  case 35:
    return "cudaErrorInsufficientDriver";
  case 36:
    return "cudaErrorCallRequiresNewerDriver";
  case 37:
    return "cudaErrorInvalidSurface";
  case 43:
    return "cudaErrorDuplicateVariableName";
  case 44:
    return "cudaErrorDuplicateTextureName";
  case 45:
    return "cudaErrorDuplicateSurfaceName";
  case 46:
    return "cudaErrorDevicesUnavailable";
  case 49:
    return "cudaErrorIncompatibleDriverContext";
  case 52:
    return "cudaErrorMissingConfiguration";
  case 53:
    return "cudaErrorPriorLaunchFailure";
  case 65:
    return "cudaErrorLaunchMaxDepthExceeded";
  case 66:
    return "cudaErrorLaunchFileScopedTex";
  case 67:
    return "cudaErrorLaunchFileScopedSurf";
  case 68:
    return "cudaErrorSyncDepthExceeded";
  case 69:
    return "cudaErrorLaunchPendingCountExceeded";
  case 98:
    return "cudaErrorInvalidDeviceFunction";
  case 100:
    return "cudaErrorNoDevice";
  case 101:
    return "cudaErrorInvalidDevice";
  case 102:
    return "cudaErrorDeviceNotLicensed";
  case 103:
    return "cudaErrorSoftwareValidityNotEstablished";
  case 127:
    return "cudaErrorStartupFailure";
  case 200:
    return "cudaErrorInvalidKernelImage";
  case 201:
    return "cudaErrorDeviceUninitialized";
  case 205:
    return "cudaErrorMapBufferObjectFailed";
  case 206:
    return "cudaErrorUnmapBufferObjectFailed";
  case 207:
    return "cudaErrorArrayIsMapped";
  case 208:
    return "cudaErrorAlreadyMapped";
  case 209:
    return "cudaErrorNoKernelImageForDevice";
  case 210:
    return "cudaErrorAlreadyAcquired";
  case 211:
    return "cudaErrorNotMapped";
  case 212:
    return "cudaErrorNotMappedAsArray";
  case 213:
    return "cudaErrorNotMappedAsPointer";
  case 214:
    return "cudaErrorECCUncorrectable";
  case 215:
    return "cudaErrorUnsupportedLimit";
  case 216:
    return "cudaErrorDeviceAlreadyInUse";
  case 217:
    return "cudaErrorPeerAccessUnsupported";
  case 218:
    return "cudaErrorInvalidPtx";
  case 219:
    return "cudaErrorInvalidGraphicsContext";
  case 220:
    return "cudaErrorNvlinkUncorrectable";
  case 221:
    return "cudaErrorJitCompilerNotFound";
  case 222:
    return "cudaErrorUnsupportedPtxVersion";
  case 223:
    return "cudaErrorJitCompilationDisabled";
  case 224:
    return "cudaErrorUnsupportedExecAffinity";
  case 225:
    return "cudaErrorUnsupportedDevSideSync";
  case 226:
    return "cudaErrorContained";
  case 300:
    return "cudaErrorInvalidSource";
  case 301:
    return "cudaErrorFileNotFound";
  case 302:
    return "cudaErrorSharedObjectSymbolNotFound";
  case 303:
    return "cudaErrorSharedObjectInitFailed";
  case 304:
    return "cudaErrorOperatingSystem";
  case 400:
    return "cudaErrorInvalidResourceHandle";
  case 401:
    return "cudaErrorIllegalState";
  case 402:
    return "cudaErrorLossyQuery";
  case 500:
    return "cudaErrorSymbolNotFound";
  case 600:
    return "cudaErrorNotReady";
  case 700:
    return "cudaErrorIllegalAddress";
  case 701:
    return "cudaErrorLaunchOutOfResources";
  case 702:
    return "cudaErrorLaunchTimeout";
  case 703:
    return "cudaErrorLaunchIncompatibleTexturing";
  case 704:
    return "cudaErrorPeerAccessAlreadyEnabled";
  case 705:
    return "cudaErrorPeerAccessNotEnabled";
  case 708:
    return "cudaErrorSetOnActiveProcess";
  case 709:
    return "cudaErrorContextIsDestroyed";
  case 710:
    return "cudaErrorAssert";
  case 711:
    return "cudaErrorTooManyPeers";
  case 712:
    return "cudaErrorHostMemoryAlreadyRegistered";
  case 713:
    return "cudaErrorHostMemoryNotRegistered";
  case 714:
    return "cudaErrorHardwareStackError";
  case 715:
    return "cudaErrorIllegalInstruction";
  case 716:
    return "cudaErrorMisalignedAddress";
  case 717:
    return "cudaErrorInvalidAddressSpace";
  case 718:
    return "cudaErrorInvalidPc";
  case 719:
    return "cudaErrorLaunchFailure";
  case 720:
    return "cudaErrorCooperativeLaunchTooLarge";
  case 721:
    return "cudaErrorTensorMemoryLeak";
  case 800:
    return "cudaErrorNotPermitted";
  case 801:
    return "cudaErrorNotSupported";
  case 802:
    return "cudaErrorSystemNotReady";
  case 803:
    return "cudaErrorSystemDriverMismatch";
  case 804:
    return "cudaErrorCompatNotSupportedOnDevice";
  case 805:
    return "cudaErrorMpsConnectionFailed";
  case 806:
    return "cudaErrorMpsRpcFailure";
  case 807:
    return "cudaErrorMpsServerNotReady";
  case 808:
    return "cudaErrorMpsMaxClientsReached";
  case 809:
    return "cudaErrorMpsMaxConnectionsReached";
  case 810:
    return "cudaErrorMpsClientTerminated";
  case 811:
    return "cudaErrorCdpNotSupported";
  case 812:
    return "cudaErrorCdpVersionMismatch";
  case 900:
    return "cudaErrorStreamCaptureUnsupported";
  case 901:
    return "cudaErrorStreamCaptureInvalidated";
  case 902:
    return "cudaErrorStreamCaptureMerge";
  case 903:
    return "cudaErrorStreamCaptureUnmatched";
  case 904:
    return "cudaErrorStreamCaptureUnjoined";
  case 905:
    return "cudaErrorStreamCaptureIsolation";
  case 906:
    return "cudaErrorStreamCaptureImplicit";
  case 907:
    return "cudaErrorCapturedEvent";
  case 908:
    return "cudaErrorStreamCaptureWrongThread";
  case 909:
    return "cudaErrorTimeout";
  case 910:
    return "cudaErrorGraphExecUpdateFailure";
  case 911:
    return "cudaErrorExternalDevice";
  case 912:
    return "cudaErrorInvalidClusterSize";
  case 913:
    return "cudaErrorFunctionNotLoaded";
  case 914:
    return "cudaErrorInvalidResourceType";
  case 915:
    return "cudaErrorInvalidResourceConfiguration";
  case 999:
    return "cudaErrorUnknown";
  default:
    return nullptr;
  }
}

// ---------------------------------------------------------------------------
// Ascend / CANN (aclError) error names.
// ---------------------------------------------------------------------------

// Static lookup table mapping aclError codes to their symbolic names. aclError
// is `typedef int` (acl_base_rt.h); 0 == ACL_SUCCESS is handled by the caller's
// `!= 0` guard, so it is not listed here. CANN has three code families:
//   - acl/acl_base_rt.h                (ACL_ERROR_*    ACL layer — the direct
//                                       return of the aclrt* functions we hook)
//   - acl/error_codes/rt_error_codes.h (ACL_ERROR_RT_* rt C runtime)
//   - acl/error_codes/ge_error_codes.h (ACL_ERROR_GE_* graph engine)
// aclrt* is a thin wrapper over the rt layer, so an RT/GE code can surface
// unchanged; all three families are listed. Avoids dlsym(); CANN has no
// code->name API (aclGetRecentErrMsg is thread-local and returns the recent
// message, not a per-code name).
static inline const char *aclErrorName(int code) {
  switch (code) {
  case 100000:
    return "ACL_ERROR_INVALID_PARAM";
  case 100001:
    return "ACL_ERROR_UNINITIALIZE";
  case 100002:
    return "ACL_ERROR_REPEAT_INITIALIZE";
  case 100003:
    return "ACL_ERROR_INVALID_FILE";
  case 100004:
    return "ACL_ERROR_WRITE_FILE";
  case 100005:
    return "ACL_ERROR_INVALID_FILE_SIZE";
  case 100006:
    return "ACL_ERROR_PARSE_FILE";
  case 100007:
    return "ACL_ERROR_FILE_MISSING_ATTR";
  case 100008:
    return "ACL_ERROR_FILE_ATTR_INVALID";
  case 100009:
    return "ACL_ERROR_INVALID_DUMP_CONFIG";
  case 100010:
    return "ACL_ERROR_INVALID_PROFILING_CONFIG";
  case 100011:
    return "ACL_ERROR_INVALID_MODEL_ID";
  case 100012:
    return "ACL_ERROR_DESERIALIZE_MODEL";
  case 100013:
    return "ACL_ERROR_PARSE_MODEL";
  case 100014:
    return "ACL_ERROR_READ_MODEL_FAILURE";
  case 100015:
    return "ACL_ERROR_MODEL_SIZE_INVALID";
  case 100016:
    return "ACL_ERROR_MODEL_MISSING_ATTR";
  case 100017:
    return "ACL_ERROR_MODEL_INPUT_NOT_MATCH";
  case 100018:
    return "ACL_ERROR_MODEL_OUTPUT_NOT_MATCH";
  case 100019:
    return "ACL_ERROR_MODEL_NOT_DYNAMIC";
  case 100020:
    return "ACL_ERROR_OP_TYPE_NOT_MATCH";
  case 100021:
    return "ACL_ERROR_OP_INPUT_NOT_MATCH";
  case 100022:
    return "ACL_ERROR_OP_OUTPUT_NOT_MATCH";
  case 100023:
    return "ACL_ERROR_OP_ATTR_NOT_MATCH";
  case 100024:
    return "ACL_ERROR_OP_NOT_FOUND";
  case 100025:
    return "ACL_ERROR_OP_LOAD_FAILED";
  case 100026:
    return "ACL_ERROR_UNSUPPORTED_DATA_TYPE";
  case 100027:
    return "ACL_ERROR_FORMAT_NOT_MATCH";
  case 100028:
    return "ACL_ERROR_BIN_SELECTOR_NOT_REGISTERED";
  case 100029:
    return "ACL_ERROR_KERNEL_NOT_FOUND";
  case 100030:
    return "ACL_ERROR_BIN_SELECTOR_ALREADY_REGISTERED";
  case 100031:
    return "ACL_ERROR_KERNEL_ALREADY_REGISTERED";
  case 100032:
    return "ACL_ERROR_INVALID_QUEUE_ID";
  case 100033:
    return "ACL_ERROR_REPEAT_SUBSCRIBE";
  case 100034:
    return "ACL_ERROR_STREAM_NOT_SUBSCRIBE";
  case 100035:
    return "ACL_ERROR_THREAD_NOT_SUBSCRIBE";
  case 100036:
    return "ACL_ERROR_WAIT_CALLBACK_TIMEOUT";
  case 100037:
    return "ACL_ERROR_REPEAT_FINALIZE";
  case 100038:
    return "ACL_ERROR_NOT_STATIC_AIPP";
  case 100039:
    return "ACL_ERROR_COMPILING_STUB_MODE";
  case 100040:
    return "ACL_ERROR_GROUP_NOT_SET";
  case 100041:
    return "ACL_ERROR_GROUP_NOT_CREATE";
  case 100042:
    return "ACL_ERROR_PROF_ALREADY_RUN";
  case 100043:
    return "ACL_ERROR_PROF_NOT_RUN";
  case 100044:
    return "ACL_ERROR_DUMP_ALREADY_RUN";
  case 100045:
    return "ACL_ERROR_DUMP_NOT_RUN";
  case 148046:
    return "ACL_ERROR_PROF_REPEAT_SUBSCRIBE";
  case 148047:
    return "ACL_ERROR_PROF_API_CONFLICT";
  case 148048:
    return "ACL_ERROR_INVALID_MAX_OPQUEUE_NUM_CONFIG";
  case 148049:
    return "ACL_ERROR_INVALID_OPP_PATH";
  case 148050:
    return "ACL_ERROR_OP_UNSUPPORTED_DYNAMIC";
  case 148051:
    return "ACL_ERROR_RELATIVE_RESOURCE_NOT_CLEARED";
  case 148052:
    return "ACL_ERROR_UNSUPPORTED_JPEG";
  case 148053:
    return "ACL_ERROR_INVALID_BUNDLE_MODEL_ID";
  case 200000:
    return "ACL_ERROR_BAD_ALLOC";
  case 200001:
    return "ACL_ERROR_API_NOT_SUPPORT";
  case 200002:
    return "ACL_ERROR_INVALID_DEVICE";
  case 200003:
    return "ACL_ERROR_MEMORY_ADDRESS_UNALIGNED";
  case 200004:
    return "ACL_ERROR_RESOURCE_NOT_MATCH";
  case 200005:
    return "ACL_ERROR_INVALID_RESOURCE_HANDLE";
  case 200006:
    return "ACL_ERROR_FEATURE_UNSUPPORTED";
  case 200007:
    return "ACL_ERROR_PROF_MODULES_UNSUPPORTED";
  case 300000:
    return "ACL_ERROR_STORAGE_OVER_LIMIT";
  case 500000:
    return "ACL_ERROR_INTERNAL_ERROR";
  case 500001:
    return "ACL_ERROR_FAILURE";
  case 500002:
    return "ACL_ERROR_GE_FAILURE";
  case 500003:
    return "ACL_ERROR_RT_FAILURE";
  case 500004:
    return "ACL_ERROR_DRV_FAILURE";
  case 500005:
    return "ACL_ERROR_PROFILING_FAILURE";
  case 107000:
    return "ACL_ERROR_RT_PARAM_INVALID";
  case 107001:
    return "ACL_ERROR_RT_INVALID_DEVICEID";
  case 107002:
    return "ACL_ERROR_RT_CONTEXT_NULL";
  case 107003:
    return "ACL_ERROR_RT_STREAM_CONTEXT";
  case 107004:
    return "ACL_ERROR_RT_MODEL_CONTEXT";
  case 107005:
    return "ACL_ERROR_RT_STREAM_MODEL";
  case 107006:
    return "ACL_ERROR_RT_EVENT_TIMESTAMP_INVALID";
  case 107007:
    return "ACL_ERROR_RT_EVENT_TIMESTAMP_REVERSAL";
  case 107008:
    return "ACL_ERROR_RT_ADDR_UNALIGNED";
  case 107009:
    return "ACL_ERROR_RT_FILE_OPEN";
  case 107010:
    return "ACL_ERROR_RT_FILE_WRITE";
  case 107011:
    return "ACL_ERROR_RT_STREAM_SUBSCRIBE";
  case 107012:
    return "ACL_ERROR_RT_THREAD_SUBSCRIBE";
  case 107013:
    return "ACL_ERROR_RT_GROUP_NOT_SET";
  case 107014:
    return "ACL_ERROR_RT_GROUP_NOT_CREATE";
  case 107015:
    return "ACL_ERROR_RT_STREAM_NO_CB_REG";
  case 107016:
    return "ACL_ERROR_RT_INVALID_MEMORY_TYPE";
  case 107017:
    return "ACL_ERROR_RT_INVALID_HANDLE";
  case 107018:
    return "ACL_ERROR_RT_INVALID_MALLOC_TYPE";
  case 107019:
    return "ACL_ERROR_RT_WAIT_TIMEOUT";
  case 107020:
    return "ACL_ERROR_RT_TASK_TIMEOUT";
  case 107021:
    return "ACL_ERROR_RT_SYSPARAMOPT_NOT_SET";
  case 107022:
    return "ACL_ERROR_RT_DEVICE_TASK_ABORT";
  case 107023:
    return "ACL_ERROR_RT_STREAM_ABORT";
  case 107024:
    return "ACL_ERROR_RT_CAPTURE_DEPENDENCY";
  case 107025:
    return "ACL_ERROR_RT_STREAM_UNJOINED";
  case 107026:
    return "ACL_ERROR_RT_MODEL_CAPTURED";
  case 107027:
    return "ACL_ERROR_RT_STREAM_CAPTURED";
  case 107028:
    return "ACL_ERROR_RT_EVENT_CAPTURED";
  case 107029:
    return "ACL_ERROR_RT_STREAM_NOT_CAPTURED";
  case 107030:
    return "ACL_ERROR_RT_CAPTURE_MODE_NOT_SUPPORT";
  case 107031:
    return "ACL_ERROR_RT_STREAM_CAPTURE_IMPLICIT";
  case 107032:
    return "ACL_ERROR_STREAM_CAPTURE_CONFLICT";
  case 107033:
    return "ACL_ERROR_STREAM_TASK_GROUP_STATUS";
  case 107034:
    return "ACL_ERROR_STREAM_TASK_GROUP_INTR";
  case 107035:
    return "ACL_ERROR_RT_TASK_ABORT_STOP";
  case 107036:
    return "ACL_ERROR_RT_STREAM_CAPTURE_UNMATCHED";
  case 107037:
    return "ACL_ERROR_RT_MODEL_RUNNING";
  case 107038:
    return "ACL_ERROR_RT_STREAM_CAPTURE_WRONG_THREAD";
  case 107039:
    return "ACL_ERROR_RT_INSUFFICIENT_INPUT_ARRAY";
  case 107040:
    return "ACL_ERROR_RT_MODEL_UPDATE_FAILED";
  case 107041:
    return "ACL_ERROR_RT_CAPTURE_MODE_BLOCK_ASYNC";
  case 107042:
    return "ACL_ERROR_RT_SYMBOL_NOT_FOUND";
  case 107043:
    return "ACL_ERROR_RT_INVALID_SYMBOL";
  case 107044:
    return "ACL_ERROR_RT_INVALID_DEVICE_FUNCTION";
  case 107045:
    return "ACL_ERROR_RT_SUB_ACLGRAPH_IS_CAPTURING";
  case 207000:
    return "ACL_ERROR_RT_FEATURE_NOT_SUPPORT";
  case 207001:
    return "ACL_ERROR_RT_MEMORY_ALLOCATION";
  case 207002:
    return "ACL_ERROR_RT_MEMORY_FREE";
  case 207003:
    return "ACL_ERROR_RT_AICORE_OVER_FLOW";
  case 207004:
    return "ACL_ERROR_RT_NO_DEVICE";
  case 207005:
    return "ACL_ERROR_RT_RESOURCE_ALLOC_FAIL";
  case 207006:
    return "ACL_ERROR_RT_NO_PERMISSION";
  case 207007:
    return "ACL_ERROR_RT_NO_EVENT_RESOURCE";
  case 207008:
    return "ACL_ERROR_RT_NO_STREAM_RESOURCE";
  case 207009:
    return "ACL_ERROR_RT_NO_NOTIFY_RESOURCE";
  case 207010:
    return "ACL_ERROR_RT_NO_MODEL_RESOURCE";
  case 207011:
    return "ACL_ERROR_RT_NO_CDQ_RESOURCE";
  case 207012:
    return "ACL_ERROR_RT_OVER_LIMIT";
  case 207013:
    return "ACL_ERROR_RT_QUEUE_EMPTY";
  case 207014:
    return "ACL_ERROR_RT_QUEUE_FULL";
  case 207015:
    return "ACL_ERROR_RT_REPEATED_INIT";
  case 207016:
    return "ACL_ERROR_RT_AIVEC_OVER_FLOW";
  case 207017:
    return "ACL_ERROR_RT_OVER_FLOW";
  case 207018:
    return "ACL_ERROR_RT_DEVICE_OOM";
  case 207019:
    return "ACL_ERROR_RT_FEATURE_NOT_SUPPORT_UPDATE_OP";
  case 207020:
    return "ACL_ERROR_RT_TIMEOUT";
  case 507000:
    return "ACL_ERROR_RT_INTERNAL_ERROR";
  case 507001:
    return "ACL_ERROR_RT_TS_ERROR";
  case 507002:
    return "ACL_ERROR_RT_STREAM_TASK_FULL";
  case 507003:
    return "ACL_ERROR_RT_STREAM_TASK_EMPTY";
  case 507004:
    return "ACL_ERROR_RT_STREAM_NOT_COMPLETE";
  case 507005:
    return "ACL_ERROR_RT_END_OF_SEQUENCE";
  case 507006:
    return "ACL_ERROR_RT_EVENT_NOT_COMPLETE";
  case 507007:
    return "ACL_ERROR_RT_CONTEXT_RELEASE_ERROR";
  case 507008:
    return "ACL_ERROR_RT_SOC_VERSION";
  case 507009:
    return "ACL_ERROR_RT_TASK_TYPE_NOT_SUPPORT";
  case 507010:
    return "ACL_ERROR_RT_LOST_HEARTBEAT";
  case 507011:
    return "ACL_ERROR_RT_MODEL_EXECUTE";
  case 507012:
    return "ACL_ERROR_RT_REPORT_TIMEOUT";
  case 507013:
    return "ACL_ERROR_RT_SYS_DMA";
  case 507014:
    return "ACL_ERROR_RT_AICORE_TIMEOUT";
  case 507015:
    return "ACL_ERROR_RT_AICORE_EXCEPTION";
  case 507016:
    return "ACL_ERROR_RT_AICORE_TRAP_EXCEPTION";
  case 507017:
    return "ACL_ERROR_RT_AICPU_TIMEOUT";
  case 507018:
    return "ACL_ERROR_RT_AICPU_EXCEPTION";
  case 507019:
    return "ACL_ERROR_RT_AICPU_DATADUMP_RSP_ERR";
  case 507020:
    return "ACL_ERROR_RT_AICPU_MODEL_RSP_ERR";
  case 507021:
    return "ACL_ERROR_RT_PROFILING_ERROR";
  case 507022:
    return "ACL_ERROR_RT_IPC_ERROR";
  case 507023:
    return "ACL_ERROR_RT_MODEL_ABORT_NORMAL";
  case 507024:
    return "ACL_ERROR_RT_KERNEL_UNREGISTERING";
  case 507025:
    return "ACL_ERROR_RT_RINGBUFFER_NOT_INIT";
  case 507026:
    return "ACL_ERROR_RT_RINGBUFFER_NO_DATA";
  case 507027:
    return "ACL_ERROR_RT_KERNEL_LOOKUP";
  case 507028:
    return "ACL_ERROR_RT_KERNEL_DUPLICATE";
  case 507029:
    return "ACL_ERROR_RT_DEBUG_REGISTER_FAIL";
  case 507030:
    return "ACL_ERROR_RT_DEBUG_UNREGISTER_FAIL";
  case 507031:
    return "ACL_ERROR_RT_LABEL_CONTEXT";
  case 507032:
    return "ACL_ERROR_RT_PROGRAM_USE_OUT";
  case 507033:
    return "ACL_ERROR_RT_DEV_SETUP_ERROR";
  case 507034:
    return "ACL_ERROR_RT_VECTOR_CORE_TIMEOUT";
  case 507035:
    return "ACL_ERROR_RT_VECTOR_CORE_EXCEPTION";
  case 507036:
    return "ACL_ERROR_RT_VECTOR_CORE_TRAP_EXCEPTION";
  case 507037:
    return "ACL_ERROR_RT_CDQ_BATCH_ABNORMAL";
  case 507038:
    return "ACL_ERROR_RT_DIE_MODE_CHANGE_ERROR";
  case 507039:
    return "ACL_ERROR_RT_DIE_SET_ERROR";
  case 507040:
    return "ACL_ERROR_RT_INVALID_DIEID";
  case 507041:
    return "ACL_ERROR_RT_DIE_MODE_NOT_SET";
  case 507042:
    return "ACL_ERROR_RT_AICORE_TRAP_READ_OVERFLOW";
  case 507043:
    return "ACL_ERROR_RT_AICORE_TRAP_WRITE_OVERFLOW";
  case 507044:
    return "ACL_ERROR_RT_VECTOR_CORE_TRAP_READ_OVERFLOW";
  case 507045:
    return "ACL_ERROR_RT_VECTOR_CORE_TRAP_WRITE_OVERFLOW";
  case 507046:
    return "ACL_ERROR_RT_STREAM_SYNC_TIMEOUT";
  case 507047:
    return "ACL_ERROR_RT_EVENT_SYNC_TIMEOUT";
  case 507048:
    return "ACL_ERROR_RT_FFTS_PLUS_TIMEOUT";
  case 507049:
    return "ACL_ERROR_RT_FFTS_PLUS_EXCEPTION";
  case 507050:
    return "ACL_ERROR_RT_FFTS_PLUS_TRAP_EXCEPTION";
  case 507051:
    return "ACL_ERROR_RT_SEND_MSG";
  case 507052:
    return "ACL_ERROR_RT_COPY_DATA";
  case 507053:
    return "ACL_ERROR_RT_DEVICE_MEM_ERROR";
  case 507054:
    return "ACL_ERROR_RT_HBM_MULTI_BIT_ECC_ERROR";
  case 507055:
    return "ACL_ERROR_RT_SUSPECT_DEVICE_MEM_ERROR";
  case 507056:
    return "ACL_ERROR_RT_LINK_ERROR";
  case 507057:
    return "ACL_ERROR_RT_SUSPECT_REMOTE_ERROR";
  case 507899:
    return "ACL_ERROR_RT_DRV_INTERNAL_ERROR";
  case 507900:
    return "ACL_ERROR_RT_AICPU_INTERNAL_ERROR";
  case 507901:
    return "ACL_ERROR_RT_SOCKET_CLOSE";
  case 507902:
    return "ACL_ERROR_RT_AICPU_INFO_LOAD_RSP_ERR";
  case 507903:
    return "ACL_ERROR_RT_STREAM_CAPTURE_INVALIDATED";
  case 507904:
    return "ACL_ERROR_RT_COMM_OP_RETRY_FAIL";
  case 507905:
    return "ACL_ERROR_SNAPSHOT_LOCK_TIMEOUT";
  case 507906:
    return "ACL_ERROR_SNAPSHOT_LOCK_FAILED";
  case 507907:
    return "ACL_ERROR_SNAPSHOT_UNLOCK_FAILED";
  case 507908:
    return "ACL_ERROR_SNAPSHOT_BACKUP_FAILED";
  case 507909:
    return "ACL_ERROR_SNAPSHOT_RESTORE_FAILED";
  case 507910:
    return "ACL_ERROR_HOST_MEMORY_ALREADY_REGISTERED";
  case 507911:
    return "ACL_ERROR_HOST_MEMORY_NOT_REGISTERED";
  case 507912:
    return "ACL_ERROR_SNAPSHOT_CALLBACK_FAILED";
  case 507913:
    return "ACL_ERROR_SNAPSHOT_REGISTER_CALLBACK_FAILED";
  case 507914:
    return "ACL_ERROR_RT_L3_PORT_ERROR";
  case 507915:
    return "ACL_ERROR_RT_CCU_TIMEOUT";
  case 507916:
    return "ACL_ERROR_RT_CCU_EXCEPTION";
  case 145000:
    return "ACL_ERROR_GE_PARAM_INVALID";
  case 145001:
    return "ACL_ERROR_GE_EXEC_NOT_INIT";
  case 145002:
    return "ACL_ERROR_GE_EXEC_MODEL_PATH_INVALID";
  case 145003:
    return "ACL_ERROR_GE_EXEC_MODEL_ID_INVALID";
  case 145006:
    return "ACL_ERROR_GE_EXEC_MODEL_DATA_SIZE_INVALID";
  case 145007:
    return "ACL_ERROR_GE_EXEC_MODEL_ADDR_INVALID";
  case 145008:
    return "ACL_ERROR_GE_EXEC_MODEL_QUEUE_ID_INVALID";
  case 145009:
    return "ACL_ERROR_GE_EXEC_LOAD_MODEL_REPEATED";
  case 145011:
    return "ACL_ERROR_GE_DYNAMIC_INPUT_ADDR_INVALID";
  case 145012:
    return "ACL_ERROR_GE_DYNAMIC_INPUT_LENGTH_INVALID";
  case 145013:
    return "ACL_ERROR_GE_DYNAMIC_BATCH_SIZE_INVALID";
  case 145014:
    return "ACL_ERROR_GE_AIPP_BATCH_EMPTY";
  case 145015:
    return "ACL_ERROR_GE_AIPP_NOT_EXIST";
  case 145016:
    return "ACL_ERROR_GE_AIPP_MODE_INVALID";
  case 145017:
    return "ACL_ERROR_GE_OP_TASK_TYPE_INVALID";
  case 145018:
    return "ACL_ERROR_GE_OP_KERNEL_TYPE_INVALID";
  case 145019:
    return "ACL_ERROR_GE_PLGMGR_PATH_INVALID";
  case 145020:
    return "ACL_ERROR_GE_FORMAT_INVALID";
  case 145021:
    return "ACL_ERROR_GE_SHAPE_INVALID";
  case 145022:
    return "ACL_ERROR_GE_DATATYPE_INVALID";
  case 245000:
    return "ACL_ERROR_GE_MEMORY_ALLOCATION";
  case 245001:
    return "ACL_ERROR_GE_MEMORY_OPERATE_FAILED";
  case 245002:
    return "ACL_ERROR_GE_DEVICE_MEMORY_OPERATE_FAILED";
  case 345102:
    return "ACL_ERROR_GE_SUBHEALTHY";
  case 345103:
    return "ACL_ERROR_GE_USER_RAISE_EXCEPTION";
  case 345104:
    return "ACL_ERROR_GE_DATA_NOT_ALIGNED";
  case 545000:
    return "ACL_ERROR_GE_INTERNAL_ERROR";
  case 545001:
    return "ACL_ERROR_GE_LOAD_MODEL";
  case 545002:
    return "ACL_ERROR_GE_EXEC_LOAD_MODEL_PARTITION_FAILED";
  case 545003:
    return "ACL_ERROR_GE_EXEC_LOAD_WEIGHT_PARTITION_FAILED";
  case 545004:
    return "ACL_ERROR_GE_EXEC_LOAD_TASK_PARTITION_FAILED";
  case 545005:
    return "ACL_ERROR_GE_EXEC_LOAD_KERNEL_PARTITION_FAILED";
  case 545006:
    return "ACL_ERROR_GE_EXEC_RELEASE_MODEL_DATA";
  case 545007:
    return "ACL_ERROR_GE_COMMAND_HANDLE";
  case 545008:
    return "ACL_ERROR_GE_GET_TENSOR_INFO";
  case 545009:
    return "ACL_ERROR_GE_UNLOAD_MODEL";
  case 545601:
    return "ACL_ERROR_GE_MODEL_EXECUTE_TIMEOUT";
  case 545602:
    return "ACL_ERROR_GE_REDEPLOYING";
  default:
    return nullptr;
  }
}

} // namespace parcagpu

#endif // COLAGPU_ERROR_H_